<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ShopsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('shops')->delete();
        
        \DB::table('shops')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Cassin, Gutkowski and Bogan Coffee',
                'description' => 'Eum doloribus nihil omnis rem nulla possimus aperiam. Impedit et suscipit est assumenda consequatur.',
                'address' => '54505 Schroeder Trace Apt. 740
Einoside, WA 71860-1940',
                'city' => 'New Aracelichester',
                'state' => 'Washington',
                'postal_code' => '07133-2136',
                'country' => 'Gambia',
                'phone' => '650.928.6533',
                'email' => 'stanley34@okuneva.net',
                'business_hours' => '{"Mon-Fri": "23:46-01:52", "Sat-Sun": "22:02-14:15"}',
                'service_areas' => '["Schmidtstad", "Dareview"]',
                'amenities' => '["ea", "veniam", "a"]',
                'logo' => 'https://via.placeholder.com/300x200.png/00ffbb?text=coffee+dolores',
                'website' => 'feest.com',
                'social_links' => '{"twitter": "https://fahey.com/aut-ipsam-eius-quisquam-labore.html", "facebook": "http://lueilwitz.biz/ut-eum-omnis-eligendi-occaecati-atque-ipsam-in.html", "instagram": "http://lakin.biz/quo-minima-sit-hic-porro.html"}',
                'loyalty_program' => '{"rewards": "Modi consequuntur error blanditiis error id.", "points_per_dollar": 1}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Koelpin-Jakubowski Coffee',
                'description' => 'Alias incidunt molestias voluptas voluptatibus earum sint. Natus ullam perferendis ut ut officiis dolore. Et repellendus in rerum quod ex omnis sint. Quaerat quos sunt quia.',
                'address' => '17910 Jaunita Lodge
Ilenehaven, WI 48038-3610',
                'city' => 'Hodkiewiczborough',
                'state' => 'New Hampshire',
                'postal_code' => '74327',
                'country' => 'Korea',
                'phone' => '540-856-7444',
                'email' => 'gjohnson@cruickshank.info',
                'business_hours' => '{"Mon-Fri": "15:47-20:58", "Sat-Sun": "09:31-08:21"}',
                'service_areas' => '["South Kirsten", "Auerberg"]',
                'amenities' => '["eius", "libero", "beatae"]',
                'logo' => 'https://via.placeholder.com/300x200.png/00ee99?text=coffee+perspiciatis',
                'website' => 'rogahn.info',
                'social_links' => '{"twitter": "https://beer.com/dicta-quia-debitis-occaecati-dolor-qui.html", "facebook": "http://spinka.org/nobis-ut-vitae-doloremque", "instagram": "https://www.cronin.net/et-qui-odio-distinctio-labore-sed-asperiores-in"}',
                'loyalty_program' => '{"rewards": "Omnis ut porro est accusamus voluptatem dolorem.", "points_per_dollar": 4}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Hilpert, Cruickshank and Parisian Coffee',
                'description' => 'Et velit fugit est quidem beatae. Magni in modi quis corrupti accusantium rerum. Voluptas at est esse rerum reprehenderit repudiandae.',
                'address' => '809 Langworth Loop
Rennerfurt, GA 59019-6767',
                'city' => 'Millerchester',
                'state' => 'South Carolina',
                'postal_code' => '42078-7954',
                'country' => 'Faroe Islands',
                'phone' => '+15205299749',
                'email' => 'kitty.runolfsson@stehr.net',
                'business_hours' => '{"Mon-Fri": "16:22-03:55", "Sat-Sun": "23:38-11:39"}',
                'service_areas' => '["Abdielchester", "South Caterina"]',
                'amenities' => '["sequi", "ipsam", "magnam"]',
                'logo' => 'https://via.placeholder.com/300x200.png/0077ff?text=coffee+voluptate',
                'website' => 'hintz.biz',
                'social_links' => '{"twitter": "http://kuphal.com/sint-et-iure-qui-voluptas-itaque.html", "facebook": "https://corwin.com/accusantium-sed-ut-dolor-minima-odit.html", "instagram": "http://price.com/similique-vel-repellendus-esse-atque-dignissimos-eius"}',
                'loyalty_program' => '{"rewards": "Unde natus neque doloremque repudiandae at illum.", "points_per_dollar": 5}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Wolff, Hackett and Kunde Coffee',
                'description' => 'Enim quia quis assumenda voluptatibus libero et. Laudantium et dicta molestiae quisquam. Quos cumque nisi aperiam veniam ratione velit laborum. Laboriosam ipsam qui voluptatem eum modi voluptas.',
                'address' => '5786 Joesph Ridges Apt. 618
Augustaville, GA 67081-9687',
                'city' => 'Hahnville',
                'state' => 'Florida',
                'postal_code' => '93592-1217',
                'country' => 'Denmark',
                'phone' => '+12797305124',
                'email' => 'hazle.mertz@welch.com',
                'business_hours' => '{"Mon-Fri": "18:04-22:21", "Sat-Sun": "02:44-20:22"}',
                'service_areas' => '["Lurafort", "Crooksbury"]',
                'amenities' => '["ut", "quis", "dignissimos"]',
                'logo' => 'https://via.placeholder.com/300x200.png/00ddaa?text=coffee+itaque',
                'website' => 'satterfield.com',
                'social_links' => '{"twitter": "http://www.rodriguez.net/accusantium-nam-voluptatum-aut-nobis-at-magni", "facebook": "http://waters.com/asperiores-aliquam-aut-nulla-consequatur", "instagram": "http://www.herman.com/a-at-eligendi-id-aut"}',
                'loyalty_program' => '{"rewards": "Debitis non impedit aperiam rerum necessitatibus ex.", "points_per_dollar": 5}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Prohaska-Okuneva Coffee',
                'description' => 'Nisi officia eligendi minima ut iusto necessitatibus qui. Delectus adipisci iste sit eaque perspiciatis quam quibusdam ut. Perspiciatis et vel omnis in pariatur magnam fuga quos. Ullam impedit est eum quasi animi. Voluptas qui vel possimus facere.',
                'address' => '7890 Frederic Springs
South Robinberg, CA 76564',
                'city' => 'Port Darby',
                'state' => 'Vermont',
                'postal_code' => '42963',
                'country' => 'Sierra Leone',
            'phone' => '(718) 574-3641',
                'email' => 'juston.muller@hermiston.com',
                'business_hours' => '{"Mon-Fri": "07:49-12:25", "Sat-Sun": "20:32-06:51"}',
                'service_areas' => '["South Gerardo", "Tysonstad"]',
                'amenities' => '["rerum", "molestiae", "fugiat"]',
                'logo' => 'https://via.placeholder.com/300x200.png/008822?text=coffee+ducimus',
                'website' => 'zemlak.com',
                'social_links' => '{"twitter": "https://www.fay.com/delectus-aut-rerum-nesciunt-commodi-molestiae-eveniet", "facebook": "http://www.stroman.info/adipisci-rerum-ratione-magni-nemo-voluptates-architecto-necessitatibus", "instagram": "http://www.mosciski.biz/"}',
                'loyalty_program' => '{"rewards": "Ratione et consequuntur quasi sint quam aliquam et.", "points_per_dollar": 4}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Ratke and Sons Coffee',
                'description' => 'Dolor laudantium libero deserunt molestiae. Quos ratione quia dolores beatae similique minus.',
                'address' => '979 Gideon Freeway
East Jayda, OH 45946-4680',
                'city' => 'Tiaview',
                'state' => 'Oregon',
                'postal_code' => '94868',
                'country' => 'Jersey',
                'phone' => '580.429.9379',
                'email' => 'homenick.ismael@mayer.com',
                'business_hours' => '{"Mon-Fri": "04:48-08:45", "Sat-Sun": "09:58-00:41"}',
                'service_areas' => '["Annatown", "North Korychester"]',
                'amenities' => '["tenetur", "voluptatem", "amet"]',
                'logo' => 'https://via.placeholder.com/300x200.png/001188?text=coffee+nemo',
                'website' => 'kirlin.com',
                'social_links' => '{"twitter": "http://mraz.com/illo-est-dicta-quia-necessitatibus-exercitationem-quaerat-itaque-velit", "facebook": "https://goldner.org/occaecati-aspernatur-provident-vitae-pariatur-nihil-dolor-quia-dolore.html", "instagram": "http://rath.com/"}',
                'loyalty_program' => '{"rewards": "Accusamus ipsa animi repellendus eos expedita velit fugit.", "points_per_dollar": 1}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Jones-Grady Coffee',
                'description' => 'Eius adipisci consequatur provident fuga hic totam. Soluta similique pariatur sit qui. Sequi qui nulla consectetur esse at. Repellendus porro eveniet magni dolores voluptatem eos.',
                'address' => '90019 Steuber Rest Apt. 422
Port Maurice, NH 84164-3181',
                'city' => 'New Adrianmouth',
                'state' => 'New York',
                'postal_code' => '16867',
                'country' => 'Greece',
            'phone' => '+1 (832) 508-8740',
                'email' => 'stevie63@mertz.com',
                'business_hours' => '{"Mon-Fri": "19:01-06:33", "Sat-Sun": "19:02-15:13"}',
                'service_areas' => '["West Koby", "New Corenetown"]',
                'amenities' => '["minus", "et", "ea"]',
                'logo' => 'https://via.placeholder.com/300x200.png/002211?text=coffee+aut',
                'website' => 'dickens.org',
                'social_links' => '{"twitter": "http://huel.biz/inventore-et-harum-quia-illo-et-nisi", "facebook": "http://lang.biz/omnis-voluptas-est-eos-dolores-qui-dolor-et-nobis", "instagram": "http://schinner.com/hic-dolore-aut-sint-deleniti-deserunt-qui-accusantium"}',
                'loyalty_program' => '{"rewards": "Et sunt et aut ut impedit expedita.", "points_per_dollar": 5}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Barrows-Towne Coffee',
                'description' => 'Eos eos quis velit assumenda quo saepe. Assumenda laborum voluptatem dolorem iste repudiandae doloremque autem culpa.',
                'address' => '246 Yazmin Lakes Suite 656
North Hebermouth, CO 70992-6017',
                'city' => 'North Mary',
                'state' => 'Indiana',
                'postal_code' => '20767-6755',
                'country' => 'Montserrat',
                'phone' => '+19149871358',
                'email' => 'francesco51@terry.com',
                'business_hours' => '{"Mon-Fri": "11:24-07:24", "Sat-Sun": "14:28-09:06"}',
                'service_areas' => '["Lake Rhianna", "East Augustusstad"]',
                'amenities' => '["optio", "qui", "dicta"]',
                'logo' => 'https://via.placeholder.com/300x200.png/00ee88?text=coffee+aut',
                'website' => 'mosciski.com',
                'social_links' => '{"twitter": "https://hintz.info/ducimus-esse-sed-eaque-quidem.html", "facebook": "https://www.hayes.net/molestiae-temporibus-et-quaerat-laborum-magnam-aut", "instagram": "http://www.runte.info/in-corporis-itaque-incidunt-tempore-voluptatem-ratione"}',
                'loyalty_program' => '{"rewards": "Sed minus alias exercitationem perspiciatis sed.", "points_per_dollar": 4}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'King-Rohan Coffee',
                'description' => 'Consectetur mollitia tempora perferendis expedita et molestias. Est ut id suscipit et expedita veritatis ab ab. Sit et minima consequatur.',
                'address' => '68167 Moen Shore Suite 318
Kaleighborough, RI 81655-7472',
                'city' => 'Konopelskimouth',
                'state' => 'Louisiana',
                'postal_code' => '97875',
                'country' => 'Bhutan',
                'phone' => '1-704-267-4872',
                'email' => 'joy83@daniel.com',
                'business_hours' => '{"Mon-Fri": "16:11-08:18", "Sat-Sun": "10:45-09:49"}',
                'service_areas' => '["Hettingerland", "Port Rogeliohaven"]',
                'amenities' => '["placeat", "saepe", "sunt"]',
                'logo' => 'https://via.placeholder.com/300x200.png/006688?text=coffee+delectus',
                'website' => 'blanda.net',
                'social_links' => '{"twitter": "http://oconner.org/dolore-qui-inventore-earum.html", "facebook": "http://www.schamberger.org/", "instagram": "https://www.collins.info/aut-asperiores-quidem-neque-sed"}',
                'loyalty_program' => '{"rewards": "Sint voluptate vitae doloribus consequuntur veniam molestiae eum commodi.", "points_per_dollar": 2}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Rogahn-Balistreri Coffee',
                'description' => 'Quo sit architecto consequatur quam perspiciatis nesciunt. Debitis fuga consectetur cum incidunt dignissimos exercitationem et laborum. Ratione assumenda consequatur voluptatem ab. Quo voluptas nisi est sit repudiandae.',
                'address' => '6924 Prohaska Falls Apt. 369
Garretport, DE 53624-3993',
                'city' => 'Hattieberg',
                'state' => 'Kansas',
                'postal_code' => '61523-3171',
                'country' => 'Equatorial Guinea',
            'phone' => '(657) 562-3914',
                'email' => 'adrienne.price@mayer.net',
                'business_hours' => '{"Mon-Fri": "19:38-14:23", "Sat-Sun": "17:03-23:05"}',
                'service_areas' => '["Keelingtown", "Hegmannport"]',
                'amenities' => '["est", "culpa", "et"]',
                'logo' => 'https://via.placeholder.com/300x200.png/0077dd?text=coffee+sed',
                'website' => 'mccullough.info',
                'social_links' => '{"twitter": "http://www.kohler.com/", "facebook": "http://sauer.info/", "instagram": "http://www.funk.com/voluptatem-magni-quod-distinctio-rem-quo-delectus"}',
                'loyalty_program' => '{"rewards": "Ipsa sit nesciunt blanditiis nisi veniam amet.", "points_per_dollar": 5}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Connelly PLC Coffee',
                'description' => 'Qui laudantium sit veritatis nihil non quidem sit. Ratione nobis sint dolores consequatur odit porro dolor aliquid. Voluptate officia facilis ut. Nisi ab consequatur voluptatem tempora et fuga laudantium.',
                'address' => '11521 May Landing
Herthastad, MN 17503-8869',
                'city' => 'East Trent',
                'state' => 'North Carolina',
                'postal_code' => '98802-5505',
                'country' => 'Austria',
                'phone' => '+1.678.836.9627',
                'email' => 'johnny.gleason@feil.com',
                'business_hours' => '{"Mon-Fri": "05:01-19:11", "Sat-Sun": "09:05-02:19"}',
                'service_areas' => '["Bradenshire", "Katelynstad"]',
                'amenities' => '["debitis", "quo", "beatae"]',
                'logo' => 'https://via.placeholder.com/300x200.png/00dd11?text=coffee+sunt',
                'website' => 'reichel.info',
                'social_links' => '{"twitter": "http://waelchi.info/", "facebook": "http://www.kuvalis.biz/", "instagram": "http://crist.info/optio-quis-odio-rerum-aliquid-laudantium-tenetur-aut-rerum.html"}',
                'loyalty_program' => '{"rewards": "Consequatur et libero laudantium rerum ut consequatur dolore.", "points_per_dollar": 4}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Yost-Lemke Coffee',
                'description' => 'Est nihil nulla consectetur qui unde. Quia eos neque tempora quia. Velit aperiam porro magni voluptatem. Et accusantium animi ut dolor vitae velit.',
                'address' => '683 McCullough Camp
Lake Giannistad, OR 46777-4544',
                'city' => 'West Shayne',
                'state' => 'Hawaii',
                'postal_code' => '14113-4323',
                'country' => 'Guinea',
                'phone' => '769-650-6832',
                'email' => 'rhiannon.beier@anderson.com',
                'business_hours' => '{"Mon-Fri": "00:12-19:55", "Sat-Sun": "12:48-09:04"}',
                'service_areas' => '["Corkerychester", "New Casperborough"]',
                'amenities' => '["quia", "maxime", "exercitationem"]',
                'logo' => 'https://via.placeholder.com/300x200.png/007711?text=coffee+qui',
                'website' => 'gottlieb.com',
                'social_links' => '{"twitter": "http://yost.net/laboriosam-quae-enim-suscipit-minima-molestiae-officiis", "facebook": "http://www.predovic.com/ea-rem-eveniet-tempore-temporibus-facere-qui-porro", "instagram": "https://www.damore.net/illo-ducimus-rerum-ut"}',
                'loyalty_program' => '{"rewards": "Expedita tempora praesentium voluptas illo.", "points_per_dollar": 3}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Emard-Littel Coffee',
                'description' => 'Eos dignissimos magni excepturi. Incidunt et possimus id eligendi illo repellat. Esse illum est facere nobis aperiam.',
                'address' => '8884 Beth Union
Wisokyhaven, NC 43740-5311',
                'city' => 'New Simone',
                'state' => 'Utah',
                'postal_code' => '76828',
                'country' => 'Tonga',
                'phone' => '262-502-6924',
                'email' => 'schmeler.evangeline@wehner.com',
                'business_hours' => '{"Mon-Fri": "23:48-04:16", "Sat-Sun": "03:35-12:16"}',
                'service_areas' => '["Bodeburgh", "Marjorieland"]',
                'amenities' => '["inventore", "et", "magnam"]',
                'logo' => 'https://via.placeholder.com/300x200.png/00dd33?text=coffee+ea',
                'website' => 'johnson.com',
                'social_links' => '{"twitter": "https://bergstrom.com/beatae-libero-consequatur-non.html", "facebook": "https://franecki.info/ea-laborum-velit-doloremque-adipisci-tempore-reprehenderit-necessitatibus.html", "instagram": "http://www.marvin.com/eligendi-quis-autem-repudiandae-temporibus-ut-eveniet.html"}',
                'loyalty_program' => '{"rewards": "Qui et voluptas nam delectus sed non.", "points_per_dollar": 1}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Fadel Ltd Coffee',
                'description' => 'Minima dolores sequi earum necessitatibus sit velit. Eos laboriosam quam ut dolore officia quo culpa. Dolores consequatur voluptatem architecto qui culpa molestias.',
                'address' => '959 Stewart Village Apt. 703
Wisozkmouth, MA 21094-8345',
                'city' => 'Rogeliochester',
                'state' => 'Connecticut',
                'postal_code' => '82030',
                'country' => 'Japan',
            'phone' => '(815) 806-8593',
                'email' => 'auer.jarret@simonis.info',
                'business_hours' => '{"Mon-Fri": "17:35-11:15", "Sat-Sun": "08:08-00:35"}',
                'service_areas' => '["Hegmannberg", "Kiehnland"]',
                'amenities' => '["dolorum", "saepe", "sed"]',
                'logo' => 'https://via.placeholder.com/300x200.png/00cc00?text=coffee+quibusdam',
                'website' => 'green.info',
                'social_links' => '{"twitter": "http://dare.com/ullam-facere-voluptate-et.html", "facebook": "https://www.miller.com/modi-at-nisi-illo-aliquam-ut-et-quod", "instagram": "http://www.herman.com/illum-non-sed-rerum-perspiciatis-in"}',
                'loyalty_program' => '{"rewards": "Voluptatem nisi voluptatem et sed.", "points_per_dollar": 5}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Williamson and Sons Coffee',
                'description' => 'Exercitationem maxime aliquid exercitationem impedit reprehenderit dignissimos. Ratione quisquam dolore aut quam. Omnis fugit iure similique aut rerum non. Aut dolor et laboriosam tempore eligendi modi.',
                'address' => '13740 Ledner Shore Suite 720
Harveyton, AR 34668',
                'city' => 'Nigelbury',
                'state' => 'Idaho',
                'postal_code' => '93487',
                'country' => 'Afghanistan',
                'phone' => '+1-402-300-2794',
                'email' => 'jairo41@dibbert.com',
                'business_hours' => '{"Mon-Fri": "21:23-23:38", "Sat-Sun": "10:28-03:20"}',
                'service_areas' => '["South Ansel", "Krisport"]',
                'amenities' => '["dolor", "omnis", "expedita"]',
                'logo' => 'https://via.placeholder.com/300x200.png/0000bb?text=coffee+et',
                'website' => 'heathcote.com',
                'social_links' => '{"twitter": "http://www.ebert.com/", "facebook": "http://hegmann.com/", "instagram": "http://www.hane.info/nihil-commodi-omnis-sed-id"}',
                'loyalty_program' => '{"rewards": "Quo et doloribus autem ea officiis sint.", "points_per_dollar": 2}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Flatley Group Coffee',
                'description' => 'Eaque adipisci voluptas error odio aliquid assumenda esse. Optio perferendis qui eos sapiente dolor voluptate ipsa. Iste ut illum molestiae et iusto perferendis molestiae maxime. Animi et quibusdam molestiae magni autem sit.',
                'address' => '18063 Jacynthe Point Apt. 394
West Emilioburgh, IA 68120',
                'city' => 'North Laurie',
                'state' => 'Iowa',
                'postal_code' => '68727',
                'country' => 'United Arab Emirates',
                'phone' => '+1.678.927.5733',
                'email' => 'dibbert.colton@douglas.net',
                'business_hours' => '{"Mon-Fri": "15:41-03:10", "Sat-Sun": "16:35-04:33"}',
                'service_areas' => '["North Gildashire", "Trinitychester"]',
                'amenities' => '["voluptatibus", "sed", "sint"]',
                'logo' => 'https://via.placeholder.com/300x200.png/0055dd?text=coffee+eos',
                'website' => 'goodwin.com',
                'social_links' => '{"twitter": "https://www.bednar.com/ut-in-repellat-sapiente-reiciendis-ratione-omnis", "facebook": "http://sporer.org/", "instagram": "https://shields.com/iusto-consequatur-totam-debitis-similique-quasi-recusandae-aliquid.html"}',
                'loyalty_program' => '{"rewards": "Adipisci ipsum ea hic et quos.", "points_per_dollar": 1}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Russel Inc Coffee',
                'description' => 'Tenetur corporis nam similique perspiciatis quae in iure. Quia animi blanditiis suscipit iste. Quisquam dolorum sequi voluptas et nulla reprehenderit.',
                'address' => '719 Edmund Hill
North Stella, DC 90184',
                'city' => 'Littlestad',
                'state' => 'Indiana',
                'postal_code' => '82698',
                'country' => 'Kiribati',
                'phone' => '339.403.1009',
                'email' => 'theresa64@rippin.biz',
                'business_hours' => '{"Mon-Fri": "03:43-06:12", "Sat-Sun": "06:00-01:05"}',
                'service_areas' => '["Botsfordhaven", "Schmitttown"]',
                'amenities' => '["quo", "quibusdam", "qui"]',
                'logo' => 'https://via.placeholder.com/300x200.png/00ff22?text=coffee+iusto',
                'website' => 'bradtke.com',
                'social_links' => '{"twitter": "https://www.lesch.com/qui-quas-et-doloremque", "facebook": "http://watsica.com/non-vel-explicabo-nulla-deleniti-rem-quo", "instagram": "http://smith.com/dolor-laudantium-ut-incidunt-dignissimos"}',
                'loyalty_program' => '{"rewards": "Perferendis reiciendis maiores est et reprehenderit esse beatae placeat.", "points_per_dollar": 1}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Roob, Nitzsche and Pfannerstill Coffee',
                'description' => 'Totam sit hic esse odit esse et modi. Cum dolorem quo pariatur iure. Rerum vel reprehenderit dolorem culpa saepe.',
                'address' => '919 Elnora Villages Suite 997
Lake Mattport, OH 21602',
                'city' => 'Braunport',
                'state' => 'Virginia',
                'postal_code' => '06630-0234',
                'country' => 'Angola',
            'phone' => '(530) 342-3786',
                'email' => 'tgislason@armstrong.com',
                'business_hours' => '{"Mon-Fri": "07:11-12:27", "Sat-Sun": "03:31-19:37"}',
                'service_areas' => '["Lubowitzfurt", "Port Danialton"]',
                'amenities' => '["sunt", "dolor", "sit"]',
                'logo' => 'https://via.placeholder.com/300x200.png/008899?text=coffee+minima',
                'website' => 'walter.com',
                'social_links' => '{"twitter": "http://www.schowalter.net/impedit-rerum-voluptates-ut-et-laborum-nisi-ex", "facebook": "https://mcdermott.com/delectus-alias-quos-aliquid.html", "instagram": "http://wintheiser.info/cupiditate-eum-ab-quos-impedit.html"}',
                'loyalty_program' => '{"rewards": "Impedit ea nihil architecto magni.", "points_per_dollar": 3}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Parker-Mraz Coffee',
                'description' => 'Eligendi illum et facere modi quaerat at. Ad delectus voluptatem qui aut expedita. Hic fugiat enim facilis deleniti et doloremque unde.',
                'address' => '9033 Lelia Mills
South Elverafort, RI 58054-6593',
                'city' => 'Camdenchester',
                'state' => 'Louisiana',
                'postal_code' => '48319-8584',
                'country' => 'Lebanon',
                'phone' => '1-731-935-9086',
                'email' => 'wbuckridge@runolfsson.com',
                'business_hours' => '{"Mon-Fri": "04:56-01:54", "Sat-Sun": "17:41-11:43"}',
                'service_areas' => '["Winnifredton", "New Kenny"]',
                'amenities' => '["exercitationem", "ut", "quae"]',
                'logo' => 'https://via.placeholder.com/300x200.png/0000ee?text=coffee+rem',
                'website' => 'considine.net',
                'social_links' => '{"twitter": "http://www.ullrich.info/pariatur-ex-consequatur-pariatur-nobis", "facebook": "http://weimann.com/", "instagram": "http://steuber.biz/sed-voluptatem-quod-perferendis-esse-dignissimos-rem-omnis.html"}',
                'loyalty_program' => '{"rewards": "Placeat id esse molestiae rerum sit quos cumque.", "points_per_dollar": 5}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Murray-Dare Coffee',
                'description' => 'Eum reiciendis molestiae et officia repudiandae. Ab alias sed in minus maxime nesciunt. Iusto rerum qui quasi voluptatem voluptatum sit doloribus similique.',
                'address' => '76251 Adonis Fork
Lucasborough, NE 20897-2804',
                'city' => 'Zulaufborough',
                'state' => 'New Jersey',
                'postal_code' => '23799',
                'country' => 'Denmark',
                'phone' => '+1-585-654-3515',
                'email' => 'runte.aryanna@hahn.biz',
                'business_hours' => '{"Mon-Fri": "18:35-21:41", "Sat-Sun": "06:38-16:34"}',
                'service_areas' => '["New Nathan", "North Matildaville"]',
                'amenities' => '["placeat", "exercitationem", "vel"]',
                'logo' => 'https://via.placeholder.com/300x200.png/006655?text=coffee+dolore',
                'website' => 'nienow.com',
                'social_links' => '{"twitter": "https://www.kovacek.com/vel-quisquam-dolorem-voluptas-ea-qui-porro", "facebook": "http://gottlieb.com/ut-sit-aperiam-labore.html", "instagram": "http://www.sawayn.org/nisi-sint-a-iusto-ea.html"}',
                'loyalty_program' => '{"rewards": "Doloribus officia placeat sit ullam.", "points_per_dollar": 3}',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}